# -*- coding: utf-8 -*-
"""CS210_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L2pwGliai64v63bkFEZ85n019Jaf2IzE
"""

import pandas as pd
from scipy.stats import pearsonr
excel_file_path = 'Data.xlsx'
sheet_name = 'Sheet1'

# Read the Excel file into a DataFrame
df = pd.read_excel(excel_file_path, sheet_name=sheet_name)
# Calculate the Pearson correlation coefficient and p-value
correlation_coefficient, p_value = pearsonr(df['weather'], df['kcal per week'])

# Print the results
print(f"Pearson Correlation Coefficient: {correlation_coefficient}")
print(f"P-value: {p_value}")

# Set the significance level
alpha = 0.05

# Check the p-value against the significance level and print the corresponding message
if p_value < alpha:
    print("Reject H0: There is no correlation between weather and kcal per week.")
else:
    print("Accept H0: There is a correlation between weather and kcal per week.")

# Create a new column with the result of dividing "kcal per week" by "weather"
df['kcal_per_week_per_weather'] = df['kcal per week'] / df['weather']

# Calculate the average of kcal_per_week_per_weather
average_kcal_per_week_per_weather = df['kcal_per_week_per_weather'].mean()
print(f"Average kcal_per_week_per_weather: {average_kcal_per_week_per_weather}")

# Check the condition for each row and print the corresponding message
for index, row in df.iterrows():
    if row['kcal_per_week_per_weather'] >= 1:
        print(f"Row {index + 1}: Reject H0")
    else:
        print(f"Row {index + 1}: Accept H0")